SET TERM ^ ;

CREATE OR ALTER PROCEDURE ANALISE_TEMPOPEDIDO
RETURNS (
    DS_ATRASO_DIA DOM_VARCHAR25,
    ATRASO_DIAS DOM_INTEGER,
    PORC_DIAS DOM_NUMERIC15_2)
AS
DECLARE VARIABLE ATRASO_1DIA DOM_INTEGER;
DECLARE VARIABLE ATRASO_2DIA DOM_INTEGER;
DECLARE VARIABLE ATRASO_3DIA DOM_INTEGER;
DECLARE VARIABLE ATRASO_4DIA DOM_INTEGER;
DECLARE VARIABLE ATRASO_5DIA DOM_INTEGER;
DECLARE VARIABLE ATRASO_6DIA DOM_INTEGER;
DECLARE VARIABLE ATRASO_7DIA DOM_INTEGER;
DECLARE VARIABLE ATRASO_MAIOR7DIA DOM_INTEGER;
DECLARE VARIABLE TOTAL_DIAS DOM_INTEGER;
BEGIN
    SELECT
        SUM(IIF(X.DTEMISSAO = DATEADD(DAY, -1, CURRENT_DATE),1,0)) ATRASO_1DIA,
        SUM(IIF(X.DTEMISSAO = DATEADD(DAY, -2, CURRENT_DATE),1,0)) ATRASO_2DIA,
        SUM(IIF(X.DTEMISSAO = DATEADD(DAY, -3, CURRENT_DATE),1,0)) ATRASO_3DIA,
        SUM(IIF(X.DTEMISSAO = DATEADD(DAY, -4, CURRENT_DATE),1,0)) ATRASO_4DIA,
        SUM(IIF(X.DTEMISSAO = DATEADD(DAY, -5, CURRENT_DATE),1,0)) ATRASO_5DIA,
        SUM(IIF(X.DTEMISSAO = DATEADD(DAY, -6, CURRENT_DATE),1,0)) ATRASO_6DIA,
        SUM(IIF(X.DTEMISSAO = DATEADD(DAY, -7, CURRENT_DATE),1,0)) ATRASO_7DIA,
        SUM(IIF(X.DTEMISSAO < DATEADD(DAY, -7, CURRENT_DATE),1,0)) ATRASO_MAIOR7DIA
    FROM (
        SELECT PP.ID, PP.DTEMISSAO, OCR.NR_EMBARQUE
        FROM PEDIDOPNEU PP
        INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.IDPEDIDOPNEU = PP.ID)
        LEFT JOIN ORDEMCARREGRECAP OCR ON (OCR.IDITEMPEDIDOPNEU = IPP.ID)
        WHERE PP.STPEDIDO <> 'C'
            AND IPP.STCANCELADO = 'N'
            AND COALESCE(OCR.ST_ORDEMCARREGRECAP, 'V') = 'V'
        GROUP BY PP.ID, PP.DTEMISSAO, OCR.NR_EMBARQUE
        )X
    INTO :ATRASO_1DIA, :ATRASO_2DIA, :ATRASO_3DIA, :ATRASO_4DIA,
         :ATRASO_5DIA, :ATRASO_6DIA, :ATRASO_7DIA, :ATRASO_MAIOR7DIA;

    BEGIN
      TOTAL_DIAS = :ATRASO_1DIA + :ATRASO_2DIA + :ATRASO_3DIA + :ATRASO_4DIA +
                    :ATRASO_5DIA + :ATRASO_6DIA + :ATRASO_7DIA + :ATRASO_MAIOR7DIA;

      DS_ATRASO_DIA = '1 DIA DE ATRASO';
      ATRASO_DIAS = :ATRASO_1DIA;
      PORC_DIAS = (:ATRASO_1DIA * 100.00) / :TOTAL_DIAS;
      SUSPEND;
   
      DS_ATRASO_DIA = '2 DIA DE ATRASO';
      ATRASO_DIAS = :ATRASO_2DIA;
      PORC_DIAS = (:ATRASO_2DIA  * 100.00) / :TOTAL_DIAS;
      SUSPEND;

      DS_ATRASO_DIA = '3 DIA DE ATRASO';
      ATRASO_DIAS = :ATRASO_3DIA;
      PORC_DIAS = (:ATRASO_3DIA  * 100.00) /:TOTAL_DIAS;
      SUSPEND;

      DS_ATRASO_DIA = '4 DIA DE ATRASO';
      ATRASO_DIAS = :ATRASO_4DIA;
      PORC_DIAS = (:ATRASO_4DIA  * 100.00) / :TOTAL_DIAS;
      SUSPEND;

      DS_ATRASO_DIA = '5 DIA DE ATRASO';
      ATRASO_DIAS = :ATRASO_5DIA;
      PORC_DIAS = (:ATRASO_5DIA * 100.00) / :TOTAL_DIAS;
      SUSPEND;

      DS_ATRASO_DIA = '6 DIA DE ATRASO';
      ATRASO_DIAS = :ATRASO_6DIA;
      PORC_DIAS = (:ATRASO_6DIA * 100.00) / :TOTAL_DIAS;
      SUSPEND;

      DS_ATRASO_DIA = '7 DIA DE ATRASO';
      ATRASO_DIAS = :ATRASO_7DIA;
      PORC_DIAS = (:ATRASO_7DIA * 100.00) / :TOTAL_DIAS;
      SUSPEND;

      DS_ATRASO_DIA = 'ACIMA DE 7 DIAS DE ATRASO';
      ATRASO_DIAS = :ATRASO_MAIOR7DIA;
      PORC_DIAS = (:ATRASO_MAIOR7DIA * 100.00) / :TOTAL_DIAS;
      SUSPEND;
    END
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT ON PEDIDOPNEU TO PROCEDURE ANALISE_TEMPOPEDIDO;
GRANT SELECT ON ITEMPEDIDOPNEU TO PROCEDURE ANALISE_TEMPOPEDIDO;
GRANT SELECT ON ORDEMCARREGRECAP TO PROCEDURE ANALISE_TEMPOPEDIDO;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE ANALISE_TEMPOPEDIDO TO SYSDBA;