SELECT
    X.EMPRESAS, X.NM_EMPRESA, X.LANCAMENTO, X.NM_PESSOA, X.TIPOCONTAS, X.CD_FORMAPGTO, X.NR_DOCUMENTO, X.VENCIMENTO,
    X.VL_DOCUMENTOS,X.VL_JUROS, X.VL_SALDOJ
FROM(-------------------------- VERIFICA AS CONTAS VENCIDAS ------------------------------------
     SELECT DISTINCT
         CONTAS.CD_EMPRESA EMPRESAS, CONTAS.CD_EMPRESA||' - '|| EMPRESA.NM_EMPRESA NM_EMPRESA, CONTAS.NR_LANCAMENTO LANCAMENTO,
         CONTAS.CD_PESSOA CD_PESSOA, P.CD_PESSOA||' - '|| P.NM_PESSOA||COALESCE(' - '||P.NM_FANTASIA,'') NM_PESSOA,
         TIPOCONTA.DS_TIPOCONTA||' - '||CONTAS.CD_TIPOCONTA DS_TIPOCONTA, CONTAS.NR_PARCELA NR_PARCELA, CONTAS.CD_TIPOCONTA TIPOCONTAS,
         CONTAS.NR_DOCUMENTO NR_DOCUMENTO, CONTAS.DT_LANCAMENTO, CONTAS.CD_FORMAPAGTO CD_FORMAPGTO,
         CONTAS.DT_VENCIMENTO VENCIMENTO, CONTAS.VL_DOCUMENTO VL_DOCUMENTOS,
         CONTAS.VL_SALDO VL_SALDO, CJ.O_VL_JURO VL_JUROS,
         CASE CONTAS.TP_CONTAS
            WHEN 'E' THEN (CJ.O_VL_JURO + (CONTAS.VL_SALDO)) 
            ELSE (CONTAS.VL_SALDO + CJ.O_VL_JURO)      
         END VL_SALDOJ,
         CONTAS.NR_DOCUMENTO||'/'||CONTAS.CD_SERIE  NR_NOTAFISCAL,
         CONTAS.NR_PARCELA||'/'||RMAX.O_NR_MAIORPARCELA  NR_PARCELACOMPOSTA, RMAX.O_NR_MAIORPARCELA MAX_PARCELA,
         CJ.O_VL_JURO VL_JURO
    FROM CONTAS 
    INNER JOIN EMPRESA ON (EMPRESA.CD_EMPRESA = CONTAS.CD_EMPRESA)        
    INNER JOIN PESSOA P ON (P.CD_PESSOA = CONTAS.CD_PESSOA)               
    
    LEFT JOIN ENDERECOPESSOA E ON (E.CD_PESSOA = P.CD_PESSOA              
                               AND E.CD_ENDERECO = (SELECT O_CD_ENDERECO  
                                                    FROM RETORNA_ENDERECO(E.CD_PESSOA, NULL))) 
    LEFT JOIN MUNICIPIO M ON (M.CD_MUNICIPIO = E.CD_MUNICIPIO)            
    INNER JOIN TIPOCONTA ON (TIPOCONTA.CD_TIPOCONTA = CONTAS.CD_TIPOCONTA)
    INNER JOIN USUARIOEMPRESA UE ON(UE.CD_USUARIO = 'admin'
                                 AND UE.CD_EMPRESA = CONTAS.CD_EMPRESA)   
    LEFT JOIN FORMAPAGTO ON (FORMAPAGTO.CD_FORMAPAGTO = CONTAS.CD_FORMAPAGTO) 
    LEFT JOIN PESSOA VEND ON (VEND.CD_PESSOA = CONTAS.CD_VENDEDOR)        
    LEFT JOIN PESSOA COBRA ON (COBRA.CD_PESSOA = CONTAS.CD_COBRADOR)      
    LEFT JOIN BANCO B ON (B.CD_BANCO = CONTAS.CD_BANCO)                   
    LEFT JOIN AGENCIA AG ON (AG.CD_BANCO = CONTAS.CD_BANCO                
                         AND AG.CD_AGENCIA = CONTAS.CD_AGENCIA)           
    LEFT JOIN JURO J ON (J.CD_JURO = COALESCE(NULL, -1)) 
    LEFT JOIN RETORNA_MAIORPARCELACONTAS(CONTAS.CD_EMPRESA, CONTAS.NR_LANCAMENTO, CONTAS.CD_PESSOA, CONTAS.CD_TIPOCONTA) RMAX ON (1=1) 
    
    LEFT JOIN CALCULA_JUROMORA(CONTAS.CD_EMPRESA, CONTAS.NR_LANCAMENTO, CONTAS.CD_PESSOA, CONTAS.CD_TIPOCONTA, CONTAS.NR_PARCELA, COALESCE(NULL, CURRENT_DATE),  Null ) CJ ON (0 = 0) 
    WHERE CONTAS.ST_CONTAS NOT IN ('A','F')
    AND  P.CD_TIPOPESSOA = (SELECT O_CD_TIPOPESSOA
                            FROM RETORNA_TIPOPESSOA_RESTRITA(CONTAS.CD_EMPRESA , 'admin', P.CD_TIPOPESSOA)) AND
        CONTAS.CD_EMPRESA = 1 AND 
        CONTAS.ST_CONTAS IN ('T','P') AND 
        CONTAS.DT_VENCIMENTO < CURRENT_DATE AND
        TIPOCONTA.CD_TIPOCONTA IN (1, 2)

    UNION

---------------------------  VERIFICA AS CONTAS QUE NÃO VENCERAM --------------------------------------------
    SELECT DISTINCT  CONTAS.CD_EMPRESA, CONTAS.CD_EMPRESA||' - '|| EMPRESA.NM_EMPRESA NM_EMPRESA, CONTAS.NR_LANCAMENTO,
           CONTAS.CD_PESSOA, P.CD_PESSOA||' - '|| P.NM_PESSOA||COALESCE(' - '||P.NM_FANTASIA,'') NM_PESSOA,     
           TIPOCONTA.DS_TIPOCONTA||' - '||CONTAS.CD_TIPOCONTA DS_TIPOCONTA, CONTAS.NR_PARCELA, CONTAS.CD_TIPOCONTA, 
             CONTAS.NR_DOCUMENTO, CONTAS.DT_LANCAMENTO, CONTAS.CD_FORMAPAGTO CD_FORMAPGTO,              
           CONTAS.DT_VENCIMENTO, CONTAS.VL_DOCUMENTO,
           CONTAS.VL_SALDO VL_SALDO, CJ.O_VL_JURO, 
           CASE CONTAS.TP_CONTAS                        
             WHEN 'E' THEN (CJ.O_VL_JURO + (CONTAS.VL_SALDO)) 
             ELSE (CONTAS.VL_SALDO + CJ.O_VL_JURO)      
           END VL_SALDOJ,                               
           CONTAS.NR_DOCUMENTO||'/'||CONTAS.CD_SERIE  NR_NOTAFISCAL, 
           CONTAS.NR_PARCELA||'/'||RMAX.O_NR_MAIORPARCELA  NR_PARCELACOMPOSTA, RMAX.O_NR_MAIORPARCELA MAX_PARCELA,  
          CJ.O_VL_JURO VL_JURO
    FROM CONTAS 
    INNER JOIN EMPRESA ON (EMPRESA.CD_EMPRESA = CONTAS.CD_EMPRESA)        
    INNER JOIN PESSOA P ON (P.CD_PESSOA = CONTAS.CD_PESSOA)               
    
    LEFT JOIN ENDERECOPESSOA E ON (E.CD_PESSOA = P.CD_PESSOA              
                               AND E.CD_ENDERECO = (SELECT O_CD_ENDERECO  
                                                    FROM RETORNA_ENDERECO(E.CD_PESSOA, NULL))) 
    LEFT JOIN MUNICIPIO M ON (M.CD_MUNICIPIO = E.CD_MUNICIPIO)            
    INNER JOIN TIPOCONTA ON (TIPOCONTA.CD_TIPOCONTA = CONTAS.CD_TIPOCONTA)
    INNER JOIN USUARIOEMPRESA UE ON(UE.CD_USUARIO = 'admin'
                                 AND UE.CD_EMPRESA = CONTAS.CD_EMPRESA)   
    LEFT JOIN FORMAPAGTO ON (FORMAPAGTO.CD_FORMAPAGTO = CONTAS.CD_FORMAPAGTO) 
    LEFT JOIN PESSOA VEND ON (VEND.CD_PESSOA = CONTAS.CD_VENDEDOR)        
    LEFT JOIN PESSOA COBRA ON (COBRA.CD_PESSOA = CONTAS.CD_COBRADOR)      
    LEFT JOIN BANCO B ON (B.CD_BANCO = CONTAS.CD_BANCO)                   
    LEFT JOIN AGENCIA AG ON (AG.CD_BANCO = CONTAS.CD_BANCO                
                         AND AG.CD_AGENCIA = CONTAS.CD_AGENCIA)           
    LEFT JOIN JURO J ON (J.CD_JURO = COALESCE(NULL, -1)) 
    LEFT JOIN RETORNA_MAIORPARCELACONTAS(CONTAS.CD_EMPRESA, CONTAS.NR_LANCAMENTO, CONTAS.CD_PESSOA, CONTAS.CD_TIPOCONTA) RMAX ON (1=1) 
    
    LEFT JOIN CALCULA_JUROMORA(CONTAS.CD_EMPRESA, CONTAS.NR_LANCAMENTO, CONTAS.CD_PESSOA, CONTAS.CD_TIPOCONTA, CONTAS.NR_PARCELA, COALESCE(NULL, CURRENT_DATE),  Null ) CJ ON (0 = 0) 
    WHERE CONTAS.ST_CONTAS NOT IN ('A','F') AND  P.CD_TIPOPESSOA = (SELECT O_CD_TIPOPESSOA FROM RETORNA_TIPOPESSOA_RESTRITA(CONTAS.CD_EMPRESA , 'admin', P.CD_TIPOPESSOA)) AND
        CONTAS.CD_EMPRESA = 1 AND 
        CONTAS.ST_CONTAS IN ('T','P') AND 
        CONTAS.DT_VENCIMENTO >= CURRENT_DATE AND
        TIPOCONTA.CD_TIPOCONTA IN (1, 2)
    ) X
ORDER BY X.TIPOCONTAS  , X.NR_DOCUMENTO, X.VENCIMENTO