SET TERM ^ ;

CREATE OR ALTER PROCEDURE CALCULATEWEEKSFORMONTH
RETURNS (
    O_SEGUNDA DOM_DATE,
    O_SEXTA DOM_DATE,
    O_SEMANA DOM_INTEGER)
AS
DECLARE VARIABLE V_CONT DOM_INTEGER;
DECLARE VARIABLE V_MES DOM_DATE;
BEGIN
    V_CONT = 1;

    V_MES = FIRSTDAYMONTH(DATEADD(MONTH,  -1, CURRENT_DATE)); --COMEÇO DO MES ANTERIOR

    WHILE (V_CONT <= 90) DO
    BEGIN
        V_MES = DATEADD(DAY, 1, V_MES);
        O_SEMANA = EXTRACT(WEEK FROM V_MES);

        IF (EXTRACT(WEEKDAY FROM V_MES) = 0) THEN
           BEGIN
               O_SEGUNDA = NULL;
               O_SEXTA = NULL;
           END
        ELSE IF (EXTRACT(WEEKDAY FROM V_MES) = 1) THEN
           BEGIN
               O_SEGUNDA = V_MES;
           END
        ELSE IF (EXTRACT(WEEKDAY FROM V_MES) = 5) THEN
           BEGIN
               O_SEXTA = V_MES;
           END

        ELSE IF (O_SEGUNDA IS NOT NULL AND O_SEXTA IS NOT NULL) THEN
           BEGIN
               SUSPEND;
           END
        V_CONT = V_CONT + 1;

    END
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT EXECUTE ON FUNCTION FIRSTDAYMONTH TO PROCEDURE CALCULATEWEEKSFORMONTH;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE CALCULATEWEEKSFORMONTH TO SYSDBA;