SET TERM ^ ;

CREATE OR ALTER FUNCTION COUNT_REPEAT (
    PARM_1 DOM_VARCHAR500 COLLATE ISO8859_1,
    PARM_2 DOM_VARCHAR500 COLLATE ISO8859_1)
RETURNS INTEGER
AS
BEGIN
  RETURN CHAR_LENGTH(:PARM_1) - CHAR_LENGTH(REPLACE(:PARM_1, :PARM_2, ''));
END^

SET TERM ; ^

COMMENT ON PARAMETER COUNT_REPEAT.PARM_1 IS
'STRING';

COMMENT ON PARAMETER COUNT_REPEAT.PARM_2 IS
'CARACTER DA OCORRENCIA';

/* Existing privileges on this procedure */

GRANT EXECUTE ON FUNCTION COUNT_REPEAT TO SYSDBA;