UPDATE PARMFATUR PF SET PF.DS_LOGOTIPO = NULL;
UPDATE CONFIGNFSE CN SET CN.DS_LOGOTIPO = NULL;
UPDATE CONFIGNFE CNE SET CNE.DS_LOGOTIPO = NULL;
UPDATE USUARIOEMPRESA UE SET UE.NM_IMAGEMFUNDO = NULL;
DELETE FROM LOGTABELA
DELETE FROM LOGCAMPO
DELETE FROM LOGMNF017
DELETE FROM LOGCONSULTAS
DELETE FROM LICENCALOG
DELETE FROM LOGMODULOS
DELETE FROM LOGAPI
DELETE FROM RELATORIO
DELETE FROM ERROLOTERPS
DELETE FROM ERROEMBARQUE
DELETE FROM ERROPEDIDORECAP
DELETE FROM CAMPOSTEMPORARIOS
