SET TERM ^ ;

create or alter procedure JV_PRODUCAODIA_V2
returns (
    O_DIA DOM_VARCHAR10,
    O_QNTD DOM_VARCHAR10,
    O_DIA_11 DOM_VARCHAR10,
    O_QNTD_11 DOM_VARCHAR10,
    O_DIA_21 DOM_VARCHAR10,
    O_QNTD_21 DOM_VARCHAR10)
as
declare variable V_NR_DIAS DOM_INTEGER;
declare variable V_ULT_DIA DOM_INTEGER;
declare variable V_MESANO DOM_VARCHAR10;
declare variable V_11_DIAS DOM_INTEGER;
declare variable V_21_DIAS DOM_INTEGER;
declare variable V_QNTD DOM_INTEGER;
declare variable V_QNTD_11 DOM_INTEGER;
declare variable V_QNTD_21 DOM_INTEGER;
declare variable V_VL_TOTAL DOM_INTEGER;
BEGIN
/******************** CRIADOR: GUSTAVO A ******************************/

  --EXTRAIR MES E ANO ATUAL
  V_MESANO = EXTRACT(MONTH FROM CURRENT_DATE) || '.' || EXTRACT(YEAR FROM CURRENT_DATE);

  V_NR_DIAS = 1; --CONTADOR DE DIAS COMEÇANDO DO DIA 1

  V_ULT_DIA = EXTRACT(DAY FROM LASTDAYMONTH(CURRENT_DATE)); --TRAZER O ULTIMO DIA DO MES

  V_VL_TOTAL = 0;

  WHILE (V_NR_DIAS <= IIF(V_ULT_DIA = 31, 11, 10)) DO
  BEGIN
     V_11_DIAS = V_NR_DIAS + 10; --COMEÇAR A CONTAR DO DIA 11 ATE 20
     V_21_DIAS = V_NR_DIAS + 20; --COMEÇAR A CONTAR DO DIA 21 ATE 31

     SELECT COUNT(OPR.ID)
     FROM ORDEMPRODUCAORECAP OPR
     INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = OPR.IDITEMPEDIDOPNEU)
     INNER JOIN ITEM II ON (IPP.IDSERVICOPNEU = II.CD_ITEM)
     INNER JOIN EXAMEFINALPNEU EX ON (EX.IDORDEMPRODUCAORECAP = OPR.ID)
     WHERE EX.DTFIM BETWEEN CAST(:V_NR_DIAS||'.'||:V_MESANO||' 00:00:00' AS TIMESTAMP)
                    AND CAST(:V_NR_DIAS||'.'||:V_MESANO||' 23:59:00' AS TIMESTAMP)
     AND OPR.IDEMPRESA = 1
     AND OPR.STEXAMEFINAL = 'A'
     AND OPR.STORDEM = 'F'
     AND IPP.STCANCELADO <> 'C'
     INTO :V_QNTD;

     SELECT COUNT(OPR.ID)
     FROM ORDEMPRODUCAORECAP OPR
     INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = OPR.IDITEMPEDIDOPNEU)
     INNER JOIN ITEM II ON (IPP.IDSERVICOPNEU = II.CD_ITEM)
     INNER JOIN EXAMEFINALPNEU EX ON (EX.IDORDEMPRODUCAORECAP = OPR.ID)
     WHERE EX.DTFIM BETWEEN CAST(:V_11_DIAS||'.'||:V_MESANO||' 00:00:00' AS TIMESTAMP)
                    AND CAST(:V_11_DIAS||'.'||:V_MESANO||' 23:59:00' AS TIMESTAMP)
     AND OPR.IDEMPRESA = 1
     AND OPR.STEXAMEFINAL = 'A'
     AND OPR.STORDEM = 'F'
     AND IPP.STCANCELADO <> 'C'
     INTO :V_QNTD_11;

     SELECT COUNT(OPR.ID)
     FROM ORDEMPRODUCAORECAP OPR
     INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = OPR.IDITEMPEDIDOPNEU)
     INNER JOIN ITEM II ON (IPP.IDSERVICOPNEU = II.CD_ITEM)
     INNER JOIN EXAMEFINALPNEU EX ON (EX.IDORDEMPRODUCAORECAP = OPR.ID)
     WHERE EX.DTFIM BETWEEN CAST(:V_21_DIAS||'.'||:V_MESANO||' 00:00:00' AS TIMESTAMP)
                    AND CAST(:V_21_DIAS||'.'||:V_MESANO||' 23:59:00' AS TIMESTAMP)
     AND OPR.IDEMPRESA = 1
     AND OPR.STEXAMEFINAL = 'A'
     AND OPR.STORDEM = 'F'
     AND IPP.STCANCELADO <> 'C'
     INTO :V_QNTD_21;

     IF (V_NR_DIAS <= 10) THEN -- MOSTRAR ATE O DIA 30
     BEGIN
          O_DIA = :V_NR_DIAS;
          O_DIA_11 = :V_11_DIAS;
          O_DIA_21 = :V_21_DIAS;

          O_QNTD = :V_QNTD;
          O_QNTD_11 = :V_QNTD_11;
          O_QNTD_21 = :V_QNTD_21;

          V_VL_TOTAL = V_VL_TOTAL + :V_QNTD + :V_QNTD_11 + :V_QNTD_21;
          SUSPEND;
     END
     IF (V_NR_DIAS = 11) THEN -- MOSTRAR O DIA 31
     BEGIN
          O_DIA_21 = :V_21_DIAS;
          O_QNTD_21 = :V_QNTD_21;
          V_VL_TOTAL = V_VL_TOTAL + :V_QNTD_21;

          O_DIA = NULL;
          O_DIA_11 = NULL;
          O_QNTD = NULL;
          O_QNTD_11 = NULL;
          SUSPEND;
     END
     IF (V_NR_DIAS = IIF(V_ULT_DIA = 31, 11, 10)) THEN
     BEGIN
          O_DIA_21 = 'Total';
          O_QNTD_21 = :V_VL_TOTAL;

          O_DIA = NULL;
          O_DIA_11 = NULL;
          O_QNTD = NULL;
          O_QNTD_11 = NULL;
          SUSPEND;
     END
     V_NR_DIAS = V_NR_DIAS + 1;
  END
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT EXECUTE ON FUNCTION LASTDAYMONTH TO PROCEDURE JV_PRODUCAODIA_V2;
GRANT SELECT ON ORDEMPRODUCAORECAP TO PROCEDURE JV_PRODUCAODIA_V2;
GRANT SELECT ON ITEMPEDIDOPNEU TO PROCEDURE JV_PRODUCAODIA_V2;
GRANT SELECT ON ITEM TO PROCEDURE JV_PRODUCAODIA_V2;
GRANT SELECT ON EXAMEFINALPNEU TO PROCEDURE JV_PRODUCAODIA_V2;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE JV_PRODUCAODIA_V2 TO SYSDBA;