SET TERM ^ ;

create or alter procedure R_ULTIMA_ETAPAPRODRECAP (
    ID_ORDEMPRODRECAP integer,
    ST_ETAPA char(1) = 'A',
    ST_EXAMEFINAL char(1) = 'A',
    ST_EXAMEINICIAL char(1) = 'G')
returns (
    CD_ULT_ETAPA DOM_INTEGER,
    DS_ULT_ETAPA DOM_VARCHAR60)
as
declare variable SEQ_ETAPAS integer;
declare variable NRORDEM integer;
declare variable DS_ETAPA DOM_VARCHAR60;
declare variable CD_ETAPA integer;
declare variable ID integer;
declare variable IDORDEMPRODUCAORECAP integer;
declare variable STEXAME DOM_CHAR1;
declare variable DTINICIO date;
declare variable DTFIM date;
BEGIN

    DS_ULT_ETAPA = NULL;
    CD_ULT_ETAPA = NULL;

    SEQ_ETAPAS = 1;

    WHILE (SEQ_ETAPAS <= 16) DO
        BEGIN
        --EXAME INICIAL--
        FOR
            SELECT
                'EXAME INICIAL' DS_ETAPA, 1 CD_ETAPAS, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                ETP.STEXAMEINICIAL STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM EXAMEINICIAL ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 1)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
                AND ETP.STEXAMEINICIAL = :ST_EXAMEINICIAL
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --RASPAGEM--
        FOR
            SELECT
                'RASPAGEM' DS_ETAPA, 2 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM RASPAGEMPNEU ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 2)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --PREPARA플O DE BANDA--
        FOR
            SELECT
                'PREPARA플O DE BANDA' DS_ETAPA, 3 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM PREPARACAOBANDAPNEU ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 3)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --ESCAREA플O--
        FOR
            SELECT
                'ESCAREA플O' DS_ETAPA, 4 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM ESCAREACAOPNEU ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 4)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --LIMPEZAMANCHAO--
        FOR
            SELECT
                'LIMPEZA MANCH홒' DS_ETAPA, 5 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM LIMPEZAMANCHAO ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 5)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --APLICA플O COLA--
        FOR
            SELECT
                'APLICA플O COLA' DS_ETAPA, 6 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM APLICACAOCOLAPNEU ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 6)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
    
        --APLICA플O CONSERTO--
        FOR
            SELECT
                'APLICA플O CONSERTO' DS_ETAPA, 7 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM APLICCONSERTOPNEU ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 7)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --EXTRUSORA--
        FOR
            SELECT
                'EXTRUSORA' DS_ETAPA, 8 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM EXTRUSORAPNEU ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 8)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --EMBORRACHAMENTO--
        FOR
            SELECT
                'EMBORRACHAMENTO' DS_ETAPA, 9 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM EMBORRACHAMENTO ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 9)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --ACABAMENTO-
        FOR
            SELECT
                'ACABAMENTO' DS_ETAPA, 10 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM ACABAMENTOPNEU ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 10)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --VULCANIZA플O--
        FOR
            SELECT
                'VULCANIZA플O' DS_ETAPA, 11 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM VULCANIZACAO ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 11)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --EXAME FINAL--
        FOR
            SELECT
                'EXAME FINAL' DS_ETAPA, 12 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                ETP.STEXAMEFINAL STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM EXAMEFINALPNEU ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 12)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
                AND ETP.STEXAMEFINAL = :ST_EXAMEFINAL
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --LIMPEZA PNEU--
        FOR
            SELECT
                'LIMPEZA PNEU' DS_ETAPA, 13 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM LIMPEZAPNEU ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 13)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --MONTAGEM--
        FOR
            SELECT
                'MONTAGEM' DS_ETAPA, 14 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM MONTAGEMRECAP ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 14)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --ENVELOPAMENTO--
        FOR
            SELECT
                'ENVELOPAMENTO' DS_ETAPA, 15 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM, EPP.NRORDEM
            FROM ENVELOPAMENTO ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 15)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END
    
        --DESENVELOPAMENTO--
        FOR
            SELECT
                'DESENVELOPAMENTO' DS_ETAPA, 16 CD_ETAPA, ETP.ID, ETP.IDORDEMPRODUCAORECAP,
                'G' STEXAME, ETP.DTINICIO, ETP.DTFIM , EPP.NRORDEM
            FROM DESENVELOPAMENTO ETP
            LEFT JOIN ETAPASPRODUCAOPNEU EPP ON (EPP.ID = 16)
            WHERE ETP.IDORDEMPRODUCAORECAP = :ID_ORDEMPRODRECAP
                AND ETP.ST_ETAPA = :ST_ETAPA
            INTO :DS_ETAPA, :CD_ETAPA, :ID, :IDORDEMPRODUCAORECAP,
            :STEXAME, :DTINICIO, :DTFIM, :NRORDEM
        DO
        BEGIN
            IF (:ID IS NOT NULL AND SEQ_ETAPAS = :NRORDEM) THEN
                BEGIN
                     DS_ULT_ETAPA = :DS_ETAPA;
                     CD_ULT_ETAPA = :CD_ETAPA;
                END
        END

        SEQ_ETAPAS = SEQ_ETAPAS + 1;
    END
    SUSPEND;
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT ON EXAMEINICIAL TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON ETAPASPRODUCAOPNEU TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON RASPAGEMPNEU TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON PREPARACAOBANDAPNEU TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON ESCAREACAOPNEU TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON LIMPEZAMANCHAO TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON APLICACAOCOLAPNEU TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON APLICCONSERTOPNEU TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON EXTRUSORAPNEU TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON EMBORRACHAMENTO TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON ACABAMENTOPNEU TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON VULCANIZACAO TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON EXAMEFINALPNEU TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON LIMPEZAPNEU TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON MONTAGEMRECAP TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON ENVELOPAMENTO TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;
GRANT SELECT ON DESENVELOPAMENTO TO PROCEDURE R_ULTIMA_ETAPAPRODRECAP;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE R_ULTIMA_ETAPAPRODRECAP TO SYSDBA;