SET TERM ^ ;

create or alter procedure RETORNA_CCB005_VIEW
returns (
    O_VL_PREVISTO DOM_NUMERIC15_2,
    O_PC_ATINGIDOALERTA DOM_NUMERIC15_2,
    O_VL_CENTROCUSTO DOM_NUMERIC15_2,
    O_PC_REALIZADO DOM_NUMERIC15_2,
    O_VL_DIFERENCA DOM_NUMERIC15_2,
    O_DS_PLANOCONTA DOM_VARCHAR250,
    O_DS_CENTROCUSTO DOM_VARCHAR250)
as
declare variable V_CD_EMPRCENTROCUSTO integer;
declare variable V_NM_EMPRESA varchar(60);
declare variable V_CD_CENTROCUSTO integer;
declare variable V_DS_CENTROCUSTO varchar(60);
declare variable V_CD_CONTA integer;
declare variable V_DT_COMPETENCIA DOM_VARCHAR10;
declare variable V_VL_PREVISTO DOM_NUMERIC15_2;
declare variable V_PC_ATINGIDOALERTA DOM_NUMERIC15_2;
declare variable V_VL_CENTROCUSTO DOM_NUMERIC15_2;
declare variable V_DS_PLANOCONTA DOM_VARCHAR250;
declare variable V_PC_REALIZADO DOM_NUMERIC15_2;
declare variable V_VL_DIFERENCA DOM_NUMERIC15_2;
BEGIN
   FOR
      SELECT
         P.CD_EMPRCENTROCUSTO, PE.NM_PESSOA NM_EMPRESA,
         P.CD_CENTROCUSTO, C.DS_CENTROCUSTO,  P.CD_CONTA, P.DT_COMPETENCIA
      FROM PLANOORCAMENTARIO P 
      INNER JOIN CENTROCUSTO C ON (C.CD_EMPRESA = P.CD_EMPRCENTROCUSTO 
                               AND C.CD_CENTROCUSTO = P.CD_CENTROCUSTO)
      INNER JOIN EMPRESA E ON (E.CD_EMPRESA = P.CD_EMPRCENTROCUSTO) 
      INNER JOIN PESSOA PE ON (PE.CD_PESSOA = E.CD_PESSOA) 
      LEFT JOIN VIEW_PLANOCONTAS(P.CD_EMPRCENTROCUSTO, ' AND P.CD_CONTA = '||P.CD_CONTA) PC ON (1=1) 
      WHERE CAST('01.'||REPLACE(P.DT_COMPETENCIA, '/','.') AS DATE) = '01.'||DATETOSTR(CURRENT_DATE, '%m.%Y')
      GROUP BY
         P.CD_EMPRCENTROCUSTO, PE.NM_PESSOA, 
         P.CD_CENTROCUSTO, C.DS_CENTROCUSTO, P.CD_CONTA, P.DT_COMPETENCIA
      ORDER BY P.CD_EMPRCENTROCUSTO, P.CD_CENTROCUSTO
      INTO :V_CD_EMPRCENTROCUSTO, :V_NM_EMPRESA, :V_CD_CENTROCUSTO,
         :V_DS_CENTROCUSTO, :V_CD_CONTA, :V_DT_COMPETENCIA
   DO
   BEGIN
      -- [VALOR PREVISTO] --
      SELECT
         P.VL_PREVISTO, P.PC_ATINGIDOALERTA, PC.DS_CONTA
      FROM PLANOORCAMENTARIO P
      INNER JOIN PLANOCONTAS PC ON (PC.CD_CONTA = P.CD_CONTA)
      WHERE P.CD_EMPRCENTROCUSTO = :V_CD_EMPRCENTROCUSTO
        AND P.CD_CENTROCUSTO     = :V_CD_CENTROCUSTO
        AND P.CD_CONTA           = :V_CD_CONTA
        AND P.DT_COMPETENCIA     = :V_DT_COMPETENCIA
      INTO :V_VL_PREVISTO, :V_PC_ATINGIDOALERTA, :V_DS_PLANOCONTA ;


      -- [VALOR REALIZADO] --
      SELECT SUM(R.VL_DOCUMENTO) VALOR
      FROM VIEW_REALIZADO_LIQUIDADO R
      WHERE R.CD_EMPRESA = :V_CD_EMPRCENTROCUSTO
        AND R.CD_CONTA = :V_CD_CONTA
     INTO :V_VL_CENTROCUSTO;

     V_PC_REALIZADO = (:V_VL_CENTROCUSTO * 100.00) / :V_VL_PREVISTO;
     V_VL_DIFERENCA = :V_VL_PREVISTO - :V_VL_CENTROCUSTO;

     O_DS_PLANOCONTA = :V_DS_PLANOCONTA;
     O_DS_CENTROCUSTO = :V_DS_CENTROCUSTO;
     O_PC_ATINGIDOALERTA = :V_PC_ATINGIDOALERTA;
     O_PC_REALIZADO = :V_PC_REALIZADO;
     O_VL_CENTROCUSTO = :V_VL_CENTROCUSTO;
     O_VL_DIFERENCA = :V_VL_DIFERENCA;
     O_VL_PREVISTO = :V_VL_PREVISTO;

     SUSPEND;

   END
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT EXECUTE ON FUNCTION DATETOSTR TO PROCEDURE RETORNA_CCB005_VIEW;
GRANT SELECT ON PLANOORCAMENTARIO TO PROCEDURE RETORNA_CCB005_VIEW;
GRANT SELECT ON CENTROCUSTO TO PROCEDURE RETORNA_CCB005_VIEW;
GRANT SELECT ON EMPRESA TO PROCEDURE RETORNA_CCB005_VIEW;
GRANT SELECT ON PESSOA TO PROCEDURE RETORNA_CCB005_VIEW;
GRANT EXECUTE ON PROCEDURE VIEW_PLANOCONTAS TO PROCEDURE RETORNA_CCB005_VIEW;
GRANT SELECT ON PLANOCONTAS TO PROCEDURE RETORNA_CCB005_VIEW;
GRANT SELECT ON VIEW_REALIZADO_LIQUIDADO TO PROCEDURE RETORNA_CCB005_VIEW;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE RETORNA_CCB005_VIEW TO SYSDBA;
