SET TERM ^ ;

create or alter procedure RETORNA_BORRACHEIRO (
    ID integer)
returns (
    NM_VENDEDOR varchar(100),
    NM_BORRACHEIRO varchar(100),
    IDBORRACHEIRO DOM_INTEGER)
as
declare variable I_CD_TIPO integer;
declare variable I_NM_VENDEDORES varchar(100);
BEGIN
/********** CRIADOR: GUSTAVO A **************/
-- input ID recebe ITEMPEDIDOPNEU.ID
  FOR
    SELECT DISTINCT P.NM_PESSOA, IPPB.CD_TIPO, IPPB.IDBORRACHEIRO
    FROM ITEMPEDIDOPNEUBORRACHEIRO IPPB
    INNER JOIN PESSOA P ON (P.CD_PESSOA = IPPB.IDBORRACHEIRO
                        AND P.ST_ATIVA = 'S')
    WHERE IPPB.IDITEMPEDIDOPNEU = :ID
    ORDER BY IPPB.CD_TIPO
    INTO :I_NM_VENDEDORES, :I_CD_TIPO, :IDBORRACHEIRO
  DO BEGIN
  IF (:I_CD_TIPO = 1) THEN
     NM_VENDEDOR = :I_NM_VENDEDORES;
  ELSE
     NM_BORRACHEIRO = :I_NM_VENDEDORES;
  SUSPEND;
  END
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT ON ITEMPEDIDOPNEUBORRACHEIRO TO PROCEDURE RETORNA_BORRACHEIRO;
GRANT SELECT ON PESSOA TO PROCEDURE RETORNA_BORRACHEIRO;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE RETORNA_BORRACHEIRO TO SYSDBA;