SET TERM ^ ;

CREATE OR ALTER PROCEDURE RETORNA_EMBARQUE_VIEW (
    I_VENDEDORES DOM_VARCHAR60)
RETURNS (
    VENDEDOR VARCHAR(60),
    NR_EMBARQUE INTEGER,
    DT_EMBARQUE DATE,
    CLIENTE VARCHAR(60),
    APROVADO BIGINT,
    REPROVADO BIGINT)
AS
DECLARE VARIABLE V_CONTADOR INTEGER;
DECLARE VARIABLE V_VENDEDOR_S DOM_VARCHAR500 COLLATE ISO8859_1;
DECLARE VARIABLE V_STRING DOM_VARCHAR500;
BEGIN
   V_CONTADOR = 1;

   V_STRING = :I_VENDEDORES;

   WHILE (V_CONTADOR <= (COUNT_REPEAT(:I_VENDEDORES, ',') + 1))
   DO
   BEGIN

      IF (V_CONTADOR < (COUNT_REPEAT(:I_VENDEDORES, ',') + 1)) THEN
         BEGIN
            V_VENDEDOR_S = SUBSTRING(V_STRING FROM 1 FOR (POSITION(',',V_STRING) - 1));
         END
      ELSE
         BEGIN
            V_VENDEDOR_S = SUBSTRING(V_STRING FROM 1 FOR 500);
         END

      FOR
      SELECT
         V.NM_PESSOA VENDEDOR, O.NR_EMBARQUE, EM.DT_EMBARQUE, P.NM_PESSOA CLIENTE,
         SUM(IIF(OPR.STEXAMEFINAL = 'A', 1, 0)) APROVADO, SUM(IIF(OPR.STEXAMEFINAL = 'R', 1, 0)) REPROVADO
      FROM ORDEMCARREGRECAP O
      INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = O.IDITEMPEDIDOPNEU)
      INNER JOIN EMBARQUE EM ON (EM.NR_EMBARQUE = O.NR_EMBARQUE
                              AND EM.CD_EMPRESA = O.CD_EMPRESA)
      INNER JOIN PEDIDOPNEU PN ON (PN.ID = IPP.IDPEDIDOPNEU)
      INNER JOIN PESSOA P ON (P.CD_PESSOA = PN.IDPESSOA)
      INNER JOIN PESSOA V ON (V.CD_PESSOA = PN.IDVENDEDOR)
      INNER JOIN ORDEMPRODUCAORECAP OPR ON (OPR.IDITEMPEDIDOPNEU = IPP.ID)
      WHERE O.ST_ORDEMCARREGRECAP = 'V'
         AND O.DT_REGISTRO >= '01.07.2023'
         AND PN.IDVENDEDOR = CAST(:V_VENDEDOR_S AS INTEGER)
      GROUP BY 1, 2, 3, 4
      INTO :VENDEDOR, :NR_EMBARQUE, :DT_EMBARQUE,
      :CLIENTE, :APROVADO, :REPROVADO

      DO
      BEGIN
         IF (:VENDEDOR IS NOT NULL) THEN
            SUSPEND;
      END

      V_STRING = SUBSTRING(V_STRING FROM (POSITION(',', V_STRING) + 1) FOR 500);
      V_CONTADOR = V_CONTADOR + 1;
   END
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT EXECUTE ON FUNCTION COUNT_REPEAT TO PROCEDURE RETORNA_EMBARQUE_VIEW;
GRANT SELECT ON ORDEMCARREGRECAP TO PROCEDURE RETORNA_EMBARQUE_VIEW;
GRANT SELECT ON ITEMPEDIDOPNEU TO PROCEDURE RETORNA_EMBARQUE_VIEW;
GRANT SELECT ON EMBARQUE TO PROCEDURE RETORNA_EMBARQUE_VIEW;
GRANT SELECT ON PEDIDOPNEU TO PROCEDURE RETORNA_EMBARQUE_VIEW;
GRANT SELECT ON PESSOA TO PROCEDURE RETORNA_EMBARQUE_VIEW;
GRANT SELECT ON ORDEMPRODUCAORECAP TO PROCEDURE RETORNA_EMBARQUE_VIEW;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE RETORNA_EMBARQUE_VIEW TO SYSDBA;