SET TERM ^ ;

CREATE OR ALTER PROCEDURE RETORNA_EMBARQUE_VIEW (
    I_VENDEDORES DOM_VARCHAR60)
RETURNS (
    VENDEDOR VARCHAR(60),
    NR_EMBARQUE INTEGER,
    DT_EMBARQUE DATE,
    CLIENTE VARCHAR(60),
    APROVADO BIGINT,
    REPROVADO BIGINT)
AS
DECLARE VARIABLE V_CONSULTA DOM_VARCHAR5000;
BEGIN
   V_CONSULTA = 'SELECT ' ||
                '     V.NM_PESSOA VENDEDOR, O.NR_EMBARQUE, EM.DT_EMBARQUE, P.NM_PESSOA CLIENTE,'  ||
                '     SUM(IIF(OPR.STEXAMEFINAL = ''A'', 1, 0)) APROVADO, SUM(IIF(OPR.STEXAMEFINAL = ''R'', 1, 0)) REPROVADO'  ||
                '  FROM ORDEMCARREGRECAP O ' ||
                '  INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = O.IDITEMPEDIDOPNEU)' ||
                '  INNER JOIN EMBARQUE EM ON (EM.NR_EMBARQUE = O.NR_EMBARQUE '  ||
                '                          AND EM.CD_EMPRESA = O.CD_EMPRESA) ' ||
                '  INNER JOIN PEDIDOPNEU PN ON (PN.ID = IPP.IDPEDIDOPNEU)  '  ||
                '  INNER JOIN PESSOA P ON (P.CD_PESSOA = PN.IDPESSOA)  '   ||
                '  INNER JOIN PESSOA V ON (V.CD_PESSOA = PN.IDVENDEDOR) '  ||
                '  INNER JOIN ORDEMPRODUCAORECAP OPR ON (OPR.IDITEMPEDIDOPNEU = IPP.ID) ' ||
                '  WHERE O.ST_ORDEMCARREGRECAP = ''V''  ' ||
                '     AND O.DT_REGISTRO >= ''01.07.2023'' ' ||
                IIF(:I_VENDEDORES = 'TODOS', '', ' AND PN.IDVENDEDOR IN ( '||:I_VENDEDORES||') ' ) ||
                --'     AND PN.IDVENDEDOR IN ( '||||' )' ||
                '  GROUP BY 1, 2, 3, 4' ;
      FOR
         EXECUTE STATEMENT V_CONSULTA
         INTO :VENDEDOR, :NR_EMBARQUE, :DT_EMBARQUE,
         :CLIENTE, :APROVADO, :REPROVADO

      DO
      BEGIN
         IF (:VENDEDOR IS NOT NULL) THEN
            SUSPEND;
      END
END^

SET TERM ; ^

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE RETORNA_EMBARQUE_VIEW TO SYSDBA;