SET TERM ^ ;

CREATE OR ALTER PROCEDURE RETORNA_RESUMO_TEMPOPEDIDO
RETURNS (
    O_DS_TEMPO DOM_VARCHAR100,
    O_QUANTIDADE DOM_INTEGER,
    O_PC_QUANTIDADE DOM_NUMERIC15_2)
AS
DECLARE VARIABLE V_PRAZO_3DIAS INTEGER;
DECLARE VARIABLE V_FORA_4DIA INTEGER;
DECLARE VARIABLE V_TOT_PRODUZIDO INTEGER;
DECLARE VARIABLE V_PC_TOTAL DOM_NUMERIC15_2;
DECLARE VARIABLE V_PC_3DIAS DOM_NUMERIC15_2;
DECLARE VARIABLE V_PC_4DIAS DOM_NUMERIC15_2;
BEGIN
    SELECT
        SUM(IIF(DATEDIFF(DAY, X.DTCOLETA, X.DTEMISSAO) <= 3,1,0)) PRAZO_3DIAS,
        SUM(IIF(DATEDIFF(DAY, X.DTCOLETA, X.DTEMISSAO) >= 4,1,0))FORA_4DIA,
        COUNT(X.NR_EMBARQUE) TOT_PRODUZIDO
    FROM (
        SELECT PP.ID, PP.DTEMISSAO DTCOLETA, OCR.NR_EMBARQUE, E.DT_EMBARQUE DTEMISSAO
        FROM PEDIDOPNEU PP
        INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.IDPEDIDOPNEU = PP.ID)
        INNER JOIN ORDEMCARREGRECAP OCR ON (OCR.IDITEMPEDIDOPNEU = IPP.ID)
        INNER JOIN EMBARQUE E ON (E.CD_EMPRESA = OCR.CD_EMPRESA
                              AND E.NR_EMBARQUE = OCR.NR_EMBARQUE)
        WHERE PP.STPEDIDO <> 'C'
            AND IPP.STCANCELADO = 'N'
            AND E.ST_EMBARQUE = 'N'
            AND E.DT_EMBARQUE BETWEEN FIRSTDAYMONTH(CURRENT_DATE)
                                  AND LASTDAYMONTH(CURRENT_DATE)
        GROUP BY PP.ID, DTEMISSAO, OCR.NR_EMBARQUE, DTCOLETA
        )X
    INTO :V_PRAZO_3DIAS, :V_FORA_4DIA, :V_TOT_PRODUZIDO;
  BEGIN
    V_PC_TOTAL = 100.00;
    V_PC_3DIAS = (:V_PRAZO_3DIAS * 100.00) / :V_TOT_PRODUZIDO;
    V_PC_4DIAS = (:V_FORA_4DIA * 100.00) / :V_TOT_PRODUZIDO;

    O_DS_TEMPO = 'TOTAL PRODUZIDO';
    O_QUANTIDADE = :V_TOT_PRODUZIDO;
    O_PC_QUANTIDADE = :V_PC_TOTAL;
    SUSPEND;

    O_DS_TEMPO = 'DENTRO DO PRAZO < 3';
    O_QUANTIDADE = :V_PC_3DIAS;
    O_PC_QUANTIDADE = :V_PC_3DIAS;
    SUSPEND;

    O_DS_TEMPO = 'FORA DO PRAZO > 4';
    O_QUANTIDADE = :V_FORA_4DIA;
    O_PC_QUANTIDADE = :V_PC_4DIAS;
    SUSPEND;
  END
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT EXECUTE ON FUNCTION FIRSTDAYMONTH TO PROCEDURE RETORNA_RESUMO_TEMPOPEDIDO;
GRANT EXECUTE ON FUNCTION LASTDAYMONTH TO PROCEDURE RETORNA_RESUMO_TEMPOPEDIDO;
GRANT SELECT ON PEDIDOPNEU TO PROCEDURE RETORNA_RESUMO_TEMPOPEDIDO;
GRANT SELECT ON ITEMPEDIDOPNEU TO PROCEDURE RETORNA_RESUMO_TEMPOPEDIDO;
GRANT SELECT ON ORDEMCARREGRECAP TO PROCEDURE RETORNA_RESUMO_TEMPOPEDIDO;
GRANT SELECT ON EMBARQUE TO PROCEDURE RETORNA_RESUMO_TEMPOPEDIDO;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE RETORNA_RESUMO_TEMPOPEDIDO TO SYSDBA;