SET SQL DIALECT 3;



SET TERM ^ ;



CREATE OR ALTER TRIGGER STFATURAAUTO_NAO FOR PEDIDOPNEU
ACTIVE AFTER INSERT POSITION 0
AS
DECLARE VARIABLE V_SG_ESTADO DOM_VARCHAR120;
BEGIN
   SELECT M.SG_ESTADO
   FROM PESSOA P
   INNER JOIN ENDERECOPESSOA EP ON (EP.CD_PESSOA = P.CD_PESSOA)
   INNER JOIN MUNICIPIO M ON (M.CD_MUNICIPIO = EP.CD_MUNICIPIO)
   WHERE P.CD_PESSOA = NEW.IDPESSOA
      AND EP.CD_ENDERECO = NEW.IDENDERECO
   GROUP BY M.SG_ESTADO
   INTO :V_SG_ESTADO;
   
   IF (:V_SG_ESTADO = 'PR') THEN
   BEGIN
      UPDATE PEDIDOPNEU PP
      SET PP.STFATURAAUTO = 'N'
      WHERE PP.ID = NEW.ID;
   END
END
^

SET TERM ; ^
