CREATE OR ALTER VIEW VIEW_ROMANEIO(
    NM_CLIENTE,
    ENDERECO_CLIENTE,
    COLETA,
    NR_NOTAFISCAL,
    NRNOTACARCSAIDA,
    DS_FORMAPAGTO,
    QNTD,
    DTEMISSAO,
    DTENTREGA,
    NR_PLACA,
    NM_MOTORISTA,
    IDVENDEDOR,
    IDPESSOA)
AS
SELECT
    PC.NM_PESSOA NM_CLIENTE, EP.DS_ENDERECO ENDERECO_CLIENTE, PN.ID COLETA,
    N.NR_NOTAFISCAL RPS_NOTA, RCNS.O_NR_NOTAFISCAL_SAIDA_CARC NRNOTACARCSAIDA,
    FPG.DS_FORMAPAGTO CONDPAGMENTO, QT_NOTA.QTIDADE QNTD,PN.DTEMISSAO DTEMISSAO, PN.DTENTREGA DTENTREGA,
    EMB.NR_PLACA NR_PLACA, P2.NM_PESSOA||' <'||P2.CD_PESSOA||'>' NM_MOTORISTA, P2.CD_PESSOA IDVENDEDOR,
    PC.CD_PESSOA IDPESSOA

FROM NOTA N 
INNER JOIN ITEMNOTA II ON (II.CD_EMPRESA = N.CD_EMPRESA 
                       AND II.NR_LANCAMENTO = N.NR_LANCAMENTO 
                       AND II.TP_NOTA = N.TP_NOTA 
                       AND II.CD_SERIE = N.CD_SERIE)

INNER JOIN (SELECT SUM(COALESCE(II.QT_ITEMNOTA, II.PS_ITEMNOTA)) QTIDADE,
                    N.NR_LANCAMENTO NRLANCAMENTO
            FROM NOTA N 
            INNER JOIN ITEMNOTA II ON (II.CD_EMPRESA = N.CD_EMPRESA
                                    AND II.NR_LANCAMENTO = N.NR_LANCAMENTO 
                                    AND II.TP_NOTA = N.TP_NOTA 
                                    AND II.CD_SERIE = N.CD_SERIE)
            WHERE N.DT_EMISSAO > CURRENT_DATE - 8
                AND N.CD_EMPRESA = 1
            GROUP BY 2) QT_NOTA ON (QT_NOTA.NRLANCAMENTO = N.NR_LANCAMENTO)

LEFT JOIN RETORNA_CHAVEPEDIDO(N.CD_EMPRESA, N.NR_LANCAMENTO, N.TP_NOTA, N.CD_SERIE) CHP ON (CHP.O_CD_ITEM = II.CD_ITEM)
INNER JOIN PLUGORDRECAPPEDIDO PLUG ON (PLUG.CD_EMPRESA = CHP.O_CD_EMPRESA 
                                   AND PLUG.NR_PEDIDO = CHP.O_NR_PEDIDO 
                                   AND PLUG.TP_PEDIDO = CHP.O_TP_PEDIDO) 
INNER JOIN ORDEMPRODUCAORECAP OPR ON (OPR.ID = PLUG.IDORDEMPRODUCAORECAP) 
INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = OPR.IDITEMPEDIDOPNEU) 
INNER JOIN PEDIDOPNEU PN ON (PN.ID = IPP.IDPEDIDOPNEU) 
INNER JOIN PESSOA PC ON (PC.CD_PESSOA = PN.IDPESSOA) 
INNER JOIN PLUGORDRECAPPEDIDO PLO ON (PLO.IDORDEMPRODUCAORECAP = OPR.ID)
INNER JOIN PEDIDO PE ON (PE.CD_EMPRESA = PLO.CD_EMPRESA
                    AND PE.NR_PEDIDO = PLO.NR_PEDIDO 
                    AND PE.TP_PEDIDO = PLO.TP_PEDIDO)
LEFT JOIN RETORNA_CHAVENOTARRC014(IPP.IDEMPRESAPEDSAI, IPP.IDPEDIDOSAI, IPP.TPPEDIDOSAI, 
                                  IPP.IDEMPRESAPEDENT, IPP.IDPEDIDOENT, IPP.TPPEDIDOENT, NULL, NULL ) RCNS ON (1=1)
INNER JOIN ENDERECOPESSOA EP ON (EP.CD_PESSOA = PC.CD_PESSOA 
                             AND EP.CD_ENDERECO = PN.IDENDERECO)
INNER JOIN FORMAPAGTO FPG ON (FPG.CD_FORMAPAGTO = N.CD_FORMAPAGTO) 
INNER JOIN NFSE NF ON (NF.CD_EMPRESA = N.CD_EMPRESA
                  AND NF.NR_LANCAMENTO = N.NR_LANCAMENTO 
                  AND NF.CD_SERIE = N.CD_SERIE 
                  AND NF.TP_NOTA = N.TP_NOTA)
INNER JOIN EMBARQUE EMB ON (EMB.NR_EMBARQUE = N.NR_EMBARQUE)
INNER JOIN PESSOA P2 ON (P2.CD_PESSOA = COALESCE(EMB.CD_TRANSPORTADOR, EMB.CD_MOTORISTA))

WHERE N.CD_EMPRESA = 1
    AND N.ST_NOTA = 'V'
    AND PN.STPEDIDO <> 'C' AND OPR.STORDEM <> 'C' 
    AND COALESCE(OPR.STORDEM, 'A') NOT IN ('C', 'T')
    AND PN.IDEMPRESA = 1
    AND PN.DTENTREGA BETWEEN CURRENT_DATE - 8 AND CURRENT_DATE + 8

GROUP BY
    NM_CLIENTE, ENDERECO_CLIENTE, COLETA,
    NF.NR_RPS, N.NR_NOTAFISCAL, NRNOTACARCSAIDA,
    FPG.DS_FORMAPAGTO, DTEMISSAO, DTENTREGA,
    NR_PLACA, NM_MOTORISTA, QNTD, IDVENDEDOR, IDPESSOA
ORDER BY NM_MOTORISTA
;