CREATE OR ALTER VIEW VIEW_RELATORIO_GERENCIAL(
    IDVENDEDOR,
    NM_VENDEDOR,
    CD_EMPRESA,
    DTEMISSAO,
    NR_NOTA,
    CPFCNPJ,
    IDPESSOA,
    NM_PESSOA,
    CD_SERVICO,
    DS_SERVICO,
    DS_GRUPO,
    DS_SUBGRUPO,
    DS_MARCA,
    QUANTIDADE,
    VL_CUSTO,
    VL_TOT_CUSTO,
    VL_UNITARIO,
    VL_TOTAL,
    VL_IMPOSTO,
    MARGEM,
    MV)
AS
SELECT
     X.IDVENDEDOR, X.NM_VENDEDOR, X.CD_EMPRESA, X.DTEMISSAO, X.NR_NOTA, X.CPFCNPJ,X.IDPESSOA, X.NM_PESSOA, X.CD_SERVICO, X.DS_SERVICO, X.DS_GRUPO,
     X.DS_SUBGRUPO, X.DS_MARCA, X.QUANTIDADE, X.VL_CUSTO, X.VL_TOT_CUSTO, X.VL_UNITARIO, X.VL_TOTAL, Y.VL_IMPOSTO,
     (X.VL_TOTAL - Y.VL_IMPOSTO - X.VL_TOT_CUSTO) MARGEM,
     IIF(X.VL_TOTAL <> 0, ((X.VL_TOTAL - Y.VL_IMPOSTO - X.VL_TOT_CUSTO) * 100 / X.VL_TOTAL), 0) MV

FROM (SELECT
          PV.CD_PESSOA IDVENDEDOR,PV.NM_PESSOA NM_VENDEDOR, N.CD_EMPRESA CD_EMPRESA, N.DT_EMISSAO DTEMISSAO, N.NR_NOTAFISCAL NR_NOTA, PV.NR_CNPJCPF CPFCNPJ,
          P.CD_PESSOA IDPESSOA, P.NM_PESSOA NM_PESSOA, ITN.CD_ITEM CD_SERVICO, I.DS_ITEM DS_SERVICO, G.DS_GRUPO DS_GRUPO, SG.DS_SUBGRUPO DS_SUBGRUPO, M.DS_MARCA DS_MARCA,
          ITN.QT_ITEMNOTA QUANTIDADE,
          CAST(R.O_VL_CUSTO AS NUMERIC(15,2)) VL_CUSTO,
          CAST((ITN.QT_ITEMNOTA * R.O_VL_CUSTO) AS NUMERIC(15,2)) VL_TOT_CUSTO,
          CAST(ITN.VL_UNITARIO AS NUMERIC(15,2)) VL_UNITARIO,
          CAST((ITN.VL_UNITARIO * ITN.QT_ITEMNOTA) AS NUMERIC(15,2)) VL_TOTAL
     FROM NOTA N
     INNER JOIN ITEMNOTA ITN ON (ITN.CD_EMPRESA = N.CD_EMPRESA
                            AND ITN.NR_LANCAMENTO = N.NR_LANCAMENTO
                            AND ITN.TP_NOTA = N.TP_NOTA
                            AND ITN.CD_SERIE = N.CD_SERIE)
     INNER JOIN VENDEDOR V ON (V.CD_VENDEDOR = N.CD_VENDEDOR)
     INNER JOIN PESSOA PV ON (PV.CD_PESSOA = V.CD_VENDEDOR)
     INNER JOIN PESSOA P ON (P.CD_PESSOA = N.CD_PESSOA)
     INNER JOIN ITEM I ON (I.CD_ITEM = ITN.CD_ITEM)
     INNER JOIN GRUPO G ON (G.CD_GRUPO = I.CD_GRUPO)
     INNER JOIN SUBGRUPO SG ON (SG.CD_SUBGRUPO = I.CD_SUBGRUPO)
     INNER JOIN MARCA M ON (M.CD_MARCA = I.CD_MARCA)
     INNER JOIN ESTOQUE E ON (E.CD_ITEM = ITN.CD_ITEM)
     INNER JOIN RETORNA_SALDOESTOQUE(1, E.CD_ITEM, E.CD_TIPOLOCAL, E.CD_LOCAL, N.DT_EMISSAO) R ON (1=1)
     WHERE I.CD_GRUPO = 1
          AND I.CD_SUBGRUPO = 101
          AND N.ST_NOTA = 'V'
          AND N.TP_NOTA = 'S'
     GROUP BY IDVENDEDOR, NM_VENDEDOR, CD_EMPRESA, DTEMISSAO, NR_NOTA, CPFCNPJ,
               IDPESSOA, NM_PESSOA, CD_SERVICO, DS_SERVICO, DS_GRUPO, DS_SUBGRUPO, DS_MARCA,
               VL_CUSTO, QUANTIDADE, VL_UNITARIO, VL_CUSTO, VL_TOT_CUSTO, VL_UNITARIO, VL_TOTAL
     ) X,

     (SELECT
          IPN.CD_ITEM CD_ITEM, SUM(IPN.VL_IMPOSTO) VL_IMPOSTO, N.CD_EMPRESA EMPRESAA,
          N.NR_NOTAFISCAL NRNOTA, N.DT_EMISSAO DTEMISSAO
     FROM NOTA N
     INNER JOIN ITEMNOTA ITN ON (ITN.CD_EMPRESA = N.CD_EMPRESA
                            AND ITN.NR_LANCAMENTO = N.NR_LANCAMENTO
                            AND ITN.TP_NOTA = N.TP_NOTA
                            AND ITN.CD_SERIE = N.CD_SERIE)
     INNER JOIN IMPOSTONOTA IPN ON (IPN.CD_EMPRESA = ITN.CD_EMPRESA
                                AND IPN.NR_LANCAMENTO = ITN.NR_LANCAMENTO
                                AND IPN.TP_NOTA = ITN.TP_NOTA
                                AND IPN.CD_SERIE = ITN.CD_SERIE
                                AND IPN.CD_ITEM = ITN.CD_ITEM)
     WHERE N.ST_NOTA = 'V'
          AND N.TP_NOTA = 'S'
     GROUP BY CD_ITEM, EMPRESAA, NRNOTA, DTEMISSAO
     ) Y
     
WHERE Y.CD_ITEM = X.CD_SERVICO
     AND Y.EMPRESAA = X.CD_EMPRESA
     AND Y.NRNOTA = X.NR_NOTA
     AND Y.DTEMISSAO = X.DTEMISSAO

GROUP BY X.IDVENDEDOR, X.NM_VENDEDOR, X.CD_EMPRESA, X.DTEMISSAO, X.NR_NOTA, X.CPFCNPJ,
          X.IDPESSOA, X.NM_PESSOA, X.CD_SERVICO,X.DS_SERVICO, X.DS_GRUPO,X.DS_SUBGRUPO,
          X.DS_MARCA, X.QUANTIDADE, X.VL_CUSTO, X.VL_TOT_CUSTO, X.VL_UNITARIO, X.VL_TOTAL, Y.VL_IMPOSTO
;