CREATE OR ALTER VIEW VIEW_PRODUCAO_GOODYEAR(
    SKU_PRODUTO,
    DSC_PRODUTO,
    MARCA_PRODUTO,
    SKU_GOODYEAR,
    ID_CLIENTE,
    ID_DISTRIBUIDOR,
    ID_FV,
    ID_FORMA_PAGAMENTO,
    QUANTIDADE_ITEM_NF_FATURA,
    VOLUME_BANDA,
    VALOR_TOTAL_ITEM_NF,
    ORDEM_PRODUCAO,
    DATA_ORDEM_PRODUCAO,
    DATA_NF,
    NUM_NF,
    SERIE_NF,
    ITEM_NF,
    OBSERVACAO,
    FLAG_ITEM_RECUSADO,
    DATA_CANCELAMENTO,
    STATUS_ORDEM_PRODUCAO,
    TIPO_SERVICO)
AS
SELECT
    I.CD_ITEM SKU_PRODUTO, I.DS_ITEM DSC_PRODUTO, MA.DS_MARCA MARCA_PRODUTO,
    I.CD_FORNECEDOR1 SKU_GOODYEAR, P.CD_PESSOA ID_CLIENTE,
    REPLACE(REPLACE(REPLACE(PE.NR_CNPJCPF, '.',''), '-',''),'/','') ID_DISTRIBUIDOR,
    N.CD_VENDEDOR ID_FV, N.CD_FORMAPAGTO ID_FORMA_PAGAMENTO, 1 QUANTIDADE_ITEM_NF_FATURA,
    VB.QTITEM VOLUME_BANDA, IT.VL_LIQUIDO VALOR_TOTAL_ITEM_NF, OPR.ID ORDEM_PRODUCAO,
    DATETOSTR(OPR.DTENTRADA, '%Y-%m-%d') DATA_ORDEM_PRODUCAO,
    DATETOSTR(N.DT_EMISSAO, '%Y-%m-%d') DATA_NF,
    N.NR_NOTAFISCAL NUM_NF, N.CD_SERIE SERIE_NF, IT.NR_SEQUENCIA ITEM_NF, N.DS_OBSERVACAO OBSERVACAO,
    IIF(OPR.STEXAMEFINAL = 'R', 1, 0) FLAG_ITEM_RECUSADO,
    IIF(N.DT_CANCELAMENTO IS NOT NULL, DATETOSTR(N.DT_CANCELAMENTO, '%Y-%m-%d'), NULL) DATA_CANCELAMENTO,
    IIF(OPR.STORDEM = 'F' AND OPR.STEXAMEFINAL = 'A', 'FATURADO', 'RECUSADO') STATUS_ORDEM_PRODUCAO,
    'RECAPAGEM' TIPO_SERVICO

FROM NOTA N
INNER JOIN ITEMNOTA IT ON (IT.CD_EMPRESA = N.CD_EMPRESA
                       AND IT.NR_LANCAMENTO = N.NR_LANCAMENTO
                       AND IT.TP_NOTA = N.TP_NOTA
                       AND IT.CD_SERIE = N.CD_SERIE)
INNER JOIN ITEM I ON (IT.CD_ITEM = I.CD_ITEM)
INNER JOIN PESSOA P ON (P.CD_PESSOA = N.CD_PESSOA)
INNER JOIN MOVIMENTACAO M ON (M.CD_MOVIMENTACAO = IT.CD_MOVIMENTACAO)
LEFT JOIN RETORNA_CHAVEPEDIDO(N.CD_EMPRESA, N.NR_LANCAMENTO, N.TP_NOTA, N.CD_SERIE) RCP ON (RCP.O_CD_ITEM = IT.CD_ITEM)
INNER JOIN PLUGORDRECAPPEDIDO POP ON(POP.CD_EMPRESA = RCP.O_CD_EMPRESA
                                  AND POP.NR_PEDIDO  = RCP.O_NR_PEDIDO
                                  AND POP.TP_PEDIDO  = RCP.O_TP_PEDIDO)
INNER JOIN ORDEMPRODUCAORECAP OPR ON(OPR.ID = POP.IDORDEMPRODUCAORECAP)
INNER JOIN ITEMPEDIDOPNEU IPP ON(IPP.ID = OPR.IDITEMPEDIDOPNEU)
INNER JOIN PNEU PN ON(PN.ID = IPP.IDPNEU)
INNER JOIN MARCA MA ON (I.CD_MARCA = MA.CD_MARCA)
INNER JOIN EMPRESA E ON (E.CD_EMPRESA = N.CD_EMPRESA)
INNER JOIN PESSOA PE ON (E.CD_PESSOA = PE.CD_PESSOA)
LEFT JOIN RVOLUME_BANDA(OPR.ID) VB ON (1=1)

WHERE N.ST_NOTA = 'V'
    AND N.TP_NOTA = 'S'
    AND N.DT_EMISSAO >= '01.01.2023'
    AND I.CD_FORNECEDOR1 IS NOT NULL
    AND I.CD_SUBGRUPO IN (708, 711)
;