/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Views                                 ****/
/******************************************************************************/


/* View: VIEW_REALIZADO_LIQUIDADO */
CREATE OR ALTER VIEW VIEW_REALIZADO_LIQUIDADO(
    DT_PROCESSO,
    CD_EMPRESA,
    NR_LANCAMENTO,
    CD_PESSOA,
    CD_TIPOCONTA,
    NR_PARCELA,
    CD_HISTORICO,
    DT_LANCAMENTO,
    DS_HISTORICO,
    TP_NATUREZA,
    CD_CONTA,
    DS_CONTA,
    VL_DOCUMENTO,
    VL_DOCUMENTO1,
    DS_OBSERVACAO,
    NM_PESSOA,
    NR_DOCUMENTO,
    TP_OPERACAO,
    TP_DOCUMENTO,
    CD_EMPRESA1,
    NR_PROCESSO,
    NR_LANCCAIXA,
    VL_PROCESSO,
    V_NR_LINHATRANSF)
AS
SELECT
         P.DT_PROCESSO, CO.CD_EMPRESA, CO.NR_LANCAMENTO, CO.CD_PESSOA, CO.CD_TIPOCONTA, CO.NR_PARCELA,
         MP.CD_HISTORICO, CO.DT_LANCAMENTO, H.DS_HISTORICO,
         H.TP_NATUREZA,
         CON.CD_CONTA, CON.DS_CONTA, MP.VL_DOCUMENTO, CO.VL_DOCUMENTO,  CO.DS_OBSERVACAO,
         PC.NM_PESSOA,CO.NR_DOCUMENTO,
         CASE WHEN CO.TP_CONTAS = 'E' THEN
                  IIF(H.TP_NATUREZA = 'R', 'P', 'R')
               WHEN CO.TP_CONTAS = 'S' THEN
                  IIF(H.TP_NATUREZA = 'P', 'R', 'P')
         END TP_OPERACAO,

         CO.TP_DOCUMENTO,
         P.CD_EMPRESA, P.NR_PROCESSO, NULL NR_LANCCAIXA, P.VL_PROCESSO, NULL V_NR_LINHATRANSF
      FROM PROCESSO P
      INNER JOIN MOVTOPROCESSO MP ON (MP.CD_EMPRESA = P.CD_EMPRESA
                                  AND MP.NR_PROCESSO = P.NR_PROCESSO)
      INNER JOIN CONTAS CO ON (CO.CD_EMPRESA = MP.CD_EMPRCONTAS
                          AND CO.NR_LANCAMENTO = MP.NR_LANCAMENTO
                          AND CO.CD_PESSOA = MP.CD_PESSOA
                          AND CO.CD_TIPOCONTA = MP.CD_TIPOCONTA
                          AND CO.NR_PARCELA = MP.NR_PARCELA)
      LEFT JOIN PESSOA PC ON (PC.CD_PESSOA = CO.CD_PESSOA)
      INNER JOIN TIPOCONTA TCO ON (TCO.CD_TIPOCONTA = CO.CD_TIPOCONTA)
      INNER JOIN HISTORICO H ON (H.CD_HISTORICO = MP.CD_HISTORICO)
      LEFT JOIN VIEW_PLANOCONTAS(MP.CD_EMPRESA, ' AND P.CD_CONTA = '||COALESCE(IIF((H.TP_NATUREZA = 'P'), COALESCE(H.CD_CONTACREDITO, H.CD_CONTADEBITO), COALESCE(H.CD_CONTADEBITO, H.CD_CONTACREDITO)),-1)) CON ON (1=1)
      WHERE P.CD_EMPRESA = 1
        AND P.ST_PROCESSO IS DISTINCT FROM  'C'
        AND P.DT_PROCESSO  BETWEEN FIRSTDAYMONTH(CURRENT_DATE) AND LASTDAYMONTH(CURRENT_DATE)
        AND 1 = IIF( ((CO.TP_DOCUMENTO IN ('CT', 'CH')) AND ('A' <> 'H')), 0, 1)

      UNION ALL

      --AVULSOS
      SELECT
         M.DT_LANCAMENTO DT_PROCESSO, NULL CD_EMPRESA, NULL NR_LANCAMENTO,  M.CD_PESSOA, NULL  CD_TIPOCONTA, NULL NR_PARCELA,
         M.CD_HISTORICO, M.DT_LANCAMENTO, H.DS_HISTORICO,
         M.TP_MOVTOCAIXA TP_NATUREZA,
         P.CD_CONTA, P.DS_CONTA, M.VL_DOCUMENTO, M.VL_DOCUMENTO,  M.DS_COMPLEMENTO,
         PC.NM_PESSOA, M.NR_DOCUMENTO, M.TP_MOVTOCAIXA TP_CONTAS, NULL TP_DOCUMENTO,
         M.CD_EMPRESA, NULL NR_PROCESSO, M.NR_LANCCAIXA, M.VL_DOCUMENTO, NULL V_NR_LINHATRANSF
      FROM MOVTOCAIXA M
      LEFT JOIN VIEW_PLANOCONTAS (M.CD_EMPRESA, 'AND P.CD_CONTA ='|| COALESCE(CASE M.TP_MOVTOCAIXA WHEN 'R' THEN COALESCE(M.CD_CONTACREDITO,M.CD_CONTADEBITO) ELSE COALESCE(M.CD_CONTADEBITO,M.CD_CONTACREDITO) END,-1)) P ON (1 = 1)
      LEFT JOIN VERIFICA_CONTA_SALDO(M.CD_EMPRESA, M.CD_CONTADEBITO, M.CD_CONTACREDITO) VCS ON (1 = 1)
      LEFT JOIN HISTORICO H ON (H.CD_HISTORICO = M.CD_HISTORICO)
      LEFT JOIN PESSOA PC ON (PC.CD_PESSOA = COALESCE(M.CD_PESSOA, M.CD_PESSOACAIXA))
      WHERE M.CD_EMPRESA = 1
      AND M.DT_LANCAMENTO BETWEEN FIRSTDAYMONTH(CURRENT_DATE) AND LASTDAYMONTH(CURRENT_DATE)
      AND M.ST_ESTORNO = 'N'
      AND M.TP_DOCUMENTO = 'AV'
      AND M.NR_PROCESSO IS NULL
      AND  VCS.O_ST_DEBCRED = 'N'

      UNION ALL

      SELECT
         M.DT_LANCAMENTO DT_PROCESSO, NULL CD_EMPRESA, NULL NR_LANCAMENTO,  M.CD_PESSOA, NULL  CD_TIPOCONTA, NULL NR_PARCELA,
         M.CD_HISTORICO, M.DT_LANCAMENTO, H.DS_HISTORICO,
         IIF(RL.O_NR_LINHA = 1, 'P', 'R') TP_NATUREZA,
         P.CD_CONTA, P.DS_CONTA, M.VL_DOCUMENTO, M.VL_DOCUMENTO,  M.DS_COMPLEMENTO,
         PC.NM_PESSOA, M.NR_DOCUMENTO, IIF(RL.O_NR_LINHA = 1, 'P', 'R')  TP_CONTAS, NULL TP_DOCUMENTO,
         M.CD_EMPRESA, NULL NR_PROCESSO, M.NR_LANCCAIXA, M.VL_DOCUMENTO, RL.O_NR_LINHA
      FROM MOVTOCAIXA M
      LEFT JOIN RETORNA_LINHAS(2) RL ON (1=1)
      LEFT JOIN VIEW_PLANOCONTAS (M.CD_EMPRESA, 'AND P.CD_CONTA ='|| COALESCE(CASE IIF(RL.O_NR_LINHA = 1, 'R', 'P') WHEN 'R' THEN COALESCE(M.CD_CONTACREDITO,M.CD_CONTADEBITO) ELSE COALESCE(M.CD_CONTADEBITO,M.CD_CONTACREDITO) END,-1)) P ON (1 = 1)
      LEFT JOIN VERIFICA_CONTA_SALDO(M.CD_EMPRESA, M.CD_CONTADEBITO, M.CD_CONTACREDITO) VCS ON (1 = 1)
      LEFT JOIN HISTORICO H ON (H.CD_HISTORICO = M.CD_HISTORICO)
      LEFT JOIN PESSOA PC ON (PC.CD_PESSOA = COALESCE(M.CD_PESSOA, M.CD_PESSOACAIXA))
      
      WHERE M.CD_EMPRESA = 1
        AND M.DT_LANCAMENTO BETWEEN FIRSTDAYMONTH(CURRENT_DATE) AND LASTDAYMONTH(CURRENT_DATE)
        AND M.ST_ESTORNO = 'N'
        AND M.TP_DOCUMENTO = 'AV'
        AND M.NR_PROCESSO IS NULL
        AND VCS.O_ST_DEBCRED = 'S'
;




/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/


/* Privileges of users */
GRANT SELECT ON MON$ATTACHMENTS TO PUBLIC;
GRANT SELECT ON MON$CALL_STACK TO PUBLIC;
GRANT SELECT ON MON$CONTEXT_VARIABLES TO PUBLIC;
GRANT SELECT ON MON$DATABASE TO PUBLIC;
GRANT SELECT ON MON$IO_STATS TO PUBLIC;
GRANT SELECT ON MON$MEMORY_USAGE TO PUBLIC;
GRANT SELECT ON MON$RECORD_STATS TO PUBLIC;
GRANT SELECT ON MON$STATEMENTS TO PUBLIC;
GRANT SELECT ON MON$TABLE_STATS TO PUBLIC;
GRANT SELECT ON MON$TRANSACTIONS TO PUBLIC;
