CREATE OR ALTER VIEW VIEW_EXATATECH_CLIENTES(
    ID_CLIENTE,
    ID_DISTRIBUIDOR,
    RAZAO_SOCIAL_CLIENTE,
    NOME_FANTASIA_CLIENTE,
    CNPJ_CPF_CLIENTE,
    COD_MUNICIPIO_IBGE_MATRIZ,
    RUA_END_MATRIZ_CLIENTE,
    NUMERO_END_MATRIZ_CLIENTE,
    COMPLEMENTO_END_MATRIZ_CLIENTE,
    CEP_END_MATRIZ_CLIENTE,
    BAIRRO_END_MATRIZ_CLIENTE,
    MUNICIPIO_END_MATRIZ_CLIENTE,
    UF_END_MATRIZ_CLIENTE,
    PAIS_END_MATRIZ_CLIENTE,
    TEL_END_MATRIZ_CLIENTE,
    EMAIL_END_MATRIZ_CLIENTE,
    PESSOA_CONTATO,
    PBU_CLIENTE,
    STATUS_FINANCEIRO_CLIENTE,
    RAMO_NEGOCIO_CLIENTE,
    FLAG_FINANCEIRO_ATIVO,
    DATA_DESATIVACAO_CLIENTE,
    FLAG_ATIVO_CLIENTE,
    CATEGORIA_CLIENTE_MERCADO,
    TIPO_CLIENTE_VENDA,
    GRUPO_ECONOMICO_CLIENTE)
AS
SELECT
    CAST(P.CD_PESSOA AS VARCHAR(50)) ID_CLIENTE,
    CAST(REPLACE(REPLACE(REPLACE(DIST.NR_CNPJCPF,'.',''),'/',''),'-','')AS VARCHAR(14)) ID_DISTRIBUIDOR,
    CAST(SUBSTRING(P.NM_PESSOA FROM 1 FOR 200) AS VARCHAR(200)) RAZAO_SOCIAL_CLIENTE,
    CAST(SUBSTRING(P.NM_FANTASIA  FROM 1 FOR 200) AS VARCHAR(200)) NOME_FANTASIA_CLIENTE,
    CAST(REPLACE(REPLACE(REPLACE(P.NR_CNPJCPF ,'.',''),'/',''),'-','')AS VARCHAR(15)) CNPJ_CPF_CLIENTE,
    CAST(M.CD_IBGE AS VARCHAR(20)) COD_MUNICIPIO_IBGE_MATRIZ,
    CAST(SUBSTRING ( E.DS_ENDERECO FROM 1 FOR 150) AS VARCHAR(150)) RUA_END_MATRIZ_CLIENTE,
    CAST(E.NR_ENDERECO AS VARCHAR(10)) NUMERO_END_MATRIZ_CLIENTE,
    CAST(SUBSTRING (E.DS_COMPLEMENTO FROM 1 FOR 100) AS VARCHAR(100)) COMPLEMENTO_END_MATRIZ_CLIENTE,
    CAST(REPLACE( SUBSTRING (E.NR_CEP  FROM 1 FOR 8) ,'-','') AS VARCHAR(8)) CEP_END_MATRIZ_CLIENTE,
    CAST(SUBSTRING (E.DS_BAIRRO  FROM 1 FOR 50) AS VARCHAR(50)) BAIRRO_END_MATRIZ_CLIENTE,
    CAST(SUBSTRING (M.DS_MUNICIPIO FROM 1 FOR 100) AS VARCHAR(100)) MUNICIPIO_END_MATRIZ_CLIENTE,
    CAST(SUBSTRING (M.SG_ESTADO FROM 1 FOR 2) AS VARCHAR(2)) UF_END_MATRIZ_CLIENTE ,
    CAST(PA.NMPAIS AS VARCHAR(100)) PAIS_END_MATRIZ_CLIENTE ,
    CAST(REPLACE(REPLACE(REPLACE(SUBSTRING (E.NR_FONE FROM 1 FOR 14),'-',''),')',''),'(','') AS VARCHAR(14)) TEL_END_MATRIZ_CLIENTE,
    CAST(SUBSTRING (P.DS_EMAIL FROM 1 FOR 50) AS VARCHAR(50)) EMAIL_END_MATRIZ_CLIENTE,
    CAST(SUBSTRING (E.DS_CONTATO  FROM 1 FOR 50) AS VARCHAR(50)) PESSOA_CONTATO,
    '?' PBU_CLIENTE, '?'  STATUS_FINANCEIRO_CLIENTE,
    CAST(SUBSTRING (R.DSRAMOATIVIDADE FROM 1 FOR 50)  AS VARCHAR(50)) RAMO_NEGOCIO_CLIENTE,
    IIF(C.NR_DUPVENC = 1, 1, 0) FLAG_FINANCEIRO_ATIVO, DATETOSTR(P.DT_INATIVADO, '%Y-%m-%d') DATA_DESATIVACAO_CLIENTE,
    IIF(P.ST_ATIVA = 'S', 1, 0) FLAG_ATIVO_CLIENTE,
    '?' CATEGORIA_CLIENTE_MERCADO ,'?' TIPO_CLIENTE_VENDA, '?' GRUPO_ECONOMICO_CLIENTE
FROM NOTA N
INNER JOIN ITEMNOTA I ON (I.CD_EMPRESA = N.CD_EMPRESA
                      AND I.NR_LANCAMENTO = N.NR_LANCAMENTO
                      AND I.TP_NOTA = N.TP_NOTA
                      AND I.CD_SERIE = N.CD_SERIE )
INNER JOIN ITEM IE ON (IE.CD_ITEM = I.CD_ITEM)
INNER JOIN PESSOA P ON (P.CD_PESSOA = N.CD_PESSOA)
INNER JOIN CREDITO C ON (C.CD_PESSOA = P.CD_PESSOA
                     AND C.CD_EMPRESA = N.CD_EMPRESA)
INNER JOIN EMPRESA EMP ON (N.CD_EMPRESA = EMP.CD_EMPRESA)
INNER JOIN PESSOA DIST ON (EMP.CD_PESSOA = DIST.CD_PESSOA)
INNER JOIN ENDERECOPESSOA E ON (P.CD_PESSOA = E.CD_PESSOA)
INNER JOIN MUNICIPIO M ON (M.CD_MUNICIPIO = E.CD_MUNICIPIO)
INNER JOIN ESTADO ES ON (ES.SG_ESTADO = M.SG_ESTADO)
INNER JOIN PAISBACEN PA ON (PA.ID = ES.IDPAIS)
LEFT JOIN RAMOATIVIDADE R ON (R.ID = P.CD_RAMOATIVIDADE)
WHERE E.NR_CEP IS NOT NULL
    AND DIST.NR_CNPJCPF IN ('28.195.956/0001-05')
GROUP BY P.CD_PESSOA, DIST.NR_CNPJCPF, P.NM_PESSOA, P.NM_FANTASIA, P.NR_CNPJCPF, M.CD_IBGE,
    E.DS_ENDERECO, E.NR_ENDERECO, E.DS_COMPLEMENTO, E.NR_CEP, E.NR_CEP, E.DS_BAIRRO, M.DS_MUNICIPIO,
    M.SG_ESTADO, PA.NMPAIS, E.NR_FONE, P.DS_EMAIL, E.DS_CONTATO, PBU_CLIENTE, R.DSRAMOATIVIDADE,
    STATUS_FINANCEIRO_CLIENTE, FLAG_FINANCEIRO_ATIVO, P.DT_CADASTRO,P.DT_INATIVADO,P.ST_ATIVA,
    CATEGORIA_CLIENTE_MERCADO, TIPO_CLIENTE_VENDA, GRUPO_ECONOMICO_CLIENTE
;