CREATE OR ALTER VIEW VIEW_EXATATECH_PRODUTOS(
    SKU_PRODUTO,
    ID_DISTRIBUIDOR,
    SKU_GOODYEAR,
    TIPO_PRODUTO,
    TIPO_PNEU,
    MARCA_PRODUTO,
    FLAG_ATIVO_PRODUTO)
AS
SELECT
    CAST (I.CD_ITEM AS VARCHAR(50)) SKU_PRODUTO,
    CAST (COALESCE(REPLACE(REPLACE(REPLACE(PE.NR_CNPJCPF,'.',''),'/',''),'-',''),'00596469000135')AS VARCHAR(14)) ID_DISTRIBUIDOR,
    CAST(COALESCE(I.CD_FORNECEDOR1,I.CD_FORNECEDOR2)AS VARCHAR(50)) SKU_GOODYEAR,
    CAST(IIF(I.DS_ITEM CONTAINING 'PN', 'PNEU', 'NAO PNEU') AS VARCHAR(200))TIPO_PRODUTO,
    IIF(G.DS_SUBGRUPO CONTAINING 'RADIAL', 'R', 'C') TIPO_PNEU, M.DS_MARCA MARCA_PRODUTO,
    IIF(I.ST_ATIVO = 'S', 1, 0) FLAG_ATIVO_PRODUTO

FROM ITEM I
LEFT JOIN ITEMPESSOA P ON (I.CD_ITEM = P.CD_ITEM)
LEFT JOIN ITEMEMPRESA E ON (E.CD_ITEM = I.CD_ITEM)
LEFT JOIN EMPRESA ES ON (ES.ST_ATIVO = 'S')
LEFT JOIN PESSOA PE ON (PE.CD_PESSOA = ES.CD_PESSOA)
INNER JOIN SUBGRUPO G ON (G.CD_SUBGRUPO = I.CD_SUBGRUPO)
INNER JOIN MARCA M ON (M.CD_MARCA = I.CD_MARCA)
WHERE PE.NR_CNPJCPF IN ('28.195.956/0001-05')
    AND I.CD_FORNECEDOR1 IS NOT NULL
GROUP BY SKU_PRODUTO, ID_DISTRIBUIDOR, SKU_GOODYEAR, TIPO_PRODUTO,
    TIPO_PNEU, MARCA_PRODUTO, FLAG_ATIVO_PRODUTO
;